- hosts: all
  name: "INSTALLING DOCKER"
  tasks:
  - name: "CREATING REPO FOR DOCKER"
    yum_repository:
      description: "repo for docker"
      name: docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no
  - name: "INSTALLING DOCKER PACKAGE"
    package:
      name: docker-ce-3:18.09.1-3.el7
      state: present
  - name: "STARTING DOCKER SERVICE"
    service:
      name: docker
      state: started
      enabled: yes
  - name: "INSTALLING DOCKER SDK"
    command: "pip3 install docker"
  - name: "PULLING DOCKER IMAGE"
    docker_image:
      name: httpd
      source: pull
  - name: "CREATING DOCKER CONTAINER"
    docker_container:
      name: webos
      image: httpd
      state: started
      detach: true
      tty: true
      ports:
      - "82:80"
      volumes:
      - /root/ansible/task1:/usr/local/apache2/htdocs/
  - name: "COPYING FILES TO THE MOUNTED DIRECTORY"
    copy:
      src: /root/ansible/index.html
      dest: /root/ansible/task1


